sudo: false
language: go
go:
  - 1.7
  - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/tcnksm/ghr
install:
  - make installdeps
script:
  - make test
after_success:
  - make all
  - make release
